# Generated by Django 5.0.4 on 2024-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_aboutme_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='img2',
            field=models.ImageField(default='default_image_path.jpg', upload_to=''),
        ),
    ]
