# Generated by Django 5.0.4 on 2024-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
