# Generated by Django 5.0.4 on 2024-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_education_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='objective',
            field=models.TextField(),
        ),
    ]
