# Generated by Django 5.0.4 on 2024-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(default='phone', max_length=10),
        ),
    ]
