# Generated by Django 5.0.4 on 2024-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_contact_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pimg', models.ImageField(upload_to='')),
                ('Pname', models.CharField(max_length=50)),
                ('Pdis', models.TextField()),
                ('plink', models.URLField()),
            ],
        ),
    ]
