# Generated by Django 5.0.4 on 2024-05-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraductionEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institiute', models.CharField(max_length=100)),
                ('cls', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=60)),
                ('place', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institiute', models.CharField(max_length=100)),
                ('cls', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=60)),
                ('place', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
