# Generated by Django 5.0.4 on 2024-05-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_graductioneducation_schooleducation_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='sklis')),
                ('image', models.ImageField(upload_to='skils')),
            ],
        ),
    ]
